# 这些是支持此项目的赞助商链接

github: [luminous-ChenXi]
patreon: # 替换为你的 Patreon 用户名
open_collective: # 替换为你的 Open Collective 用户名
ko_fi: # 替换为你的 Ko-fi 用户名
tidelift: # 替换为你的 Tidelift 平台名称
community_bridge: # 替换为你的 Community Bridge 项目名称
liberapay: # 替换为你的 Liberapay 用户名
issuehunt: # 替换为你的 IssueHunt 用户名
otechie: # 替换为你的 Otechie 用户名
lfx_crowdfunding: # 替换为你的 LFX Crowdfunding 项目名称
custom: # 替换为你的自定义赞助链接