import http from './http'

export const createChenxiCaptcha = () => http.post('/api/auth/chenxi/captcha', {})
export const verifyChenxiCaptcha = (payload) => http.post('/api/auth/chenxi/captcha/verify', payload)
export const requestRegisterCode = (payload) => http.post('/api/auth/chenxi/register/code', payload)
export const registerChenxiAccount = (payload) => http.post('/api/auth/chenxi/register', payload)
export const requestResetCode = (payload) => http.post('/api/auth/chenxi/password/code', payload)
export const resetChenxiPassword = (payload) => http.post('/api/auth/chenxi/password/reset', payload)
export const fetchMailConfig = () => http.get('/api/admin/chenxi/mail-config')
export const updateMailConfig = (payload) => http.put('/api/admin/chenxi/mail-config', payload)
export const testMailConfig = (targetEmail) => http.post('/api/admin/chenxi/mail-config/test', { targetEmail })
export const checkEmailAvailability = (email) => http.get(`/api/auth/chenxi/check-email?email=${email}`)
export const fetchMailTemplates = () => http.get('/api/admin/chenxi/mail-templates')
export const createMailTemplate = (payload) => http.post('/api/admin/chenxi/mail-templates', payload)
export const updateMailTemplate = (id, payload) => http.put(`/api/admin/chenxi/mail-templates/${id}`, payload)
export const deleteMailTemplate = (id) => http.delete(`/api/admin/chenxi/mail-templates/${id}`)
export const testMailTemplate = (id, payload) => http.post(`/api/admin/chenxi/mail-templates/${id}/test`, payload)
